let stockProductos = [
    {id: 1, nombre: "Fornite", tipo: "shooter", desc: "", precio: 1200, img: '/img/.jpg', cantidad:1},
    {id: 2, nombre: "Halo 5", tipo: "shooter", desc: "", precio: 1100, img: '/img/.jpg', cantidad:1},
    {id: 3, nombre: "Halo 5", tipo: "shooter", desc: "", precio: 1200, img: '/img/.jpg', cantidad:1},
    {id: 4, nombre: "Halo 5", tipo: "shooter", desc: "", precio: 1400, img: '/img/.jpg', cantidad:1},
    {id: 5, nombre: "Dying Light 2", tipo: "shooter", desc: "", precio: 1200, img: '/img/.jpg', cantidad:1},
    {id: 6, nombre: "Fornite", tipo: "shooter", desc: "", precio: 1500, img: '/img/.jpg', cantidad:1},
    {id: 7, nombre: "R", tipo: "", desc: "", precio: 500, img: '/img/.jpg', cantidad:1},
    {id: 8, nombre: "R", tipo: "", desc: "", precio: 500, img: '/img/.jpg', cantidad:1},
    {id: 9, nombre: "R", tipo: "", desc: "",precio: 500, img: '/img/.jpg', cantidad:1},
    {id: 10, nombre: "R", tipo: "", desc: "", precio: 700, img: '/img/.jpg', cantidad:1},
    {id: 11, nombre: "R", tipo: "", desc: "", precio: 700, img: '/img/.jpg', cantidad:1},
    {id: 12, nombre: "R", tipo: "", desc: "", precio: 700, img: '/img/.jpg', cantidad:1},
    {id: 13, nombre: "f", tipo: "c", desc: "", precio: 900, img: '/img/.jpg', cantidad:1},
    {id: 14, nombre: "f", tipo: "c", desc: "", precio: 1400, img: '/img/.jpg', cantidad:1},
    {id: 15, nombre: "f", tipo: "c", desc: "", precio: 7000, img: '/img/.jpg', cantidad:1},
    {id: 16, nombre: "f", tipo: "c", desc: "", precio: 777, img: '/img/.jpg', cantidad:1},
    {id: 17, nombre: "f", tipo: "c", desc: "", precio: 234, img: '/img/.jpg', cantidad:1},
    {id: 18, nombre: "f", tipo: "c", desc: "", precio: 1600, img: '/img/.jpg', cantidad:1},
    {id: 19, nombre: "", tipo: "ofertas", desc: "", precio: 1600, img: '/img/.jpg', cantidad:1},
    {id: 20, nombre: "", tipo: "ofertas", desc: "", precio: 3200, img: '/img/.jpg', cantidad:1},
    {id: 21, nombre: "", tipo: "ofertas", desc: "", precio: 2300, img: '/img/.jpg', cantidad:1},
    {id: 22, nombre: "", tipo: "ofertas", desc: "", precio: 5600, img: '/img/.jpg', cantidad:1},
    {id: 23, nombre: "", tipo: "ofertas", desc: "", precio: 1700, img: '/img/.jpg', cantidad:1},
    {id: 24, nombre: "", tipo: "ofertas", desc: "", precio: 800, img: '/img/.jpg', cantidad:1},
]

